server:
  port: 8181
LOG4J_FILE_PATH: /home/suresh/Desktop/logs
log:
  file-path: /home/suresh/Desktop/logs
  mode: S  ## S- Standalone, C - Centralized
  topic: logging-topic-dev
  storage-type: file  ## file, db
  database-type: nosql  ## sql, nosql
  enable-product-based-logging: false  ## true, false
  logging-level-default: TRACE ## TRACE, DEBUG, INFO, WARN, ERROR, FATAL
  logging-level-enabled: TRACE ## TRACE, DEBUG, INFO, WARN, ERROR, FATAL
kafka:
   consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: group1
      topics: logging-topic
      beanCreation: false
   producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      beanCreation: false
